// <auto-generated />
using System;
using DAL.DBModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(PaymentsDbContext))]
    partial class PaymentsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DAL.DBModels.TransactionDTO", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("TransactionID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Amount");

                    b.Property<string>("ExternalId")
                        .HasColumnName("ExternalID")
                        .HasMaxLength(50);

                    b.Property<string>("Instrument")
                        .HasMaxLength(20);

                    b.Property<string>("Metadata")
                        .HasMaxLength(1000);

                    b.Property<int>("OrderId")
                        .HasColumnName("OrderID");

                    b.Property<string>("Response")
                        .HasMaxLength(4000);

                    b.Property<string>("Status")
                        .HasMaxLength(30);

                    b.Property<DateTime>("TransactionTime")
                        .HasColumnType("datetime");

                    b.Property<string>("TransactionType")
                        .HasMaxLength(20);

                    b.Property<int>("UserId")
                        .HasColumnName("UserID");

                    b.Property<int>("VendorId")
                        .HasColumnName("VendorID");

                    b.HasKey("TransactionId")
                        .HasName("PK__Transacctions_$Id");

                    b.HasIndex("UserId", "VendorId", "ExternalId", "OrderId")
                        .HasName("in_Transactions_$orderId$userId$vendorId$externalId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("DAL.DBModels.UserDTO", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("UserID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnName("Email")
                        .HasMaxLength(50);

                    b.Property<string>("ExternalId")
                        .HasColumnName("ExternalID")
                        .HasMaxLength(50);

                    b.Property<string>("UserToken")
                        .HasMaxLength(50);

                    b.HasKey("UserId")
                        .HasName("PK__Users__Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
